name: Cross-Platform Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"
  release:
    types: [created]

jobs:
  release:
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
            artifact_name: myapp-linux-x86_64
          - os: ubuntu-24.04
            target: aarch64-unknown-linux-musl
            artifact_name: myapp-linux-arm64

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: myapp-windows-x86_64.exe
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            artifact_name: myapp-windows-arm64.exe

          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: myapp-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: myapp-macos-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true

      - name: Prepare Artifact
        shell: bash
        run: |
          mv "target/${{ matrix.target }}/release/$BIN_NAME" "${{ matrix.artifact_name }}"

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
